import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import "./styles/animate.min.css"
import "./styles/style.css"
import "./styles/style_anim.css"
import "./styles/bootstrap-vCaDZZbr.css"
import "./styles/themesv2-DZZF_N8v.css"
import "./styles/extra1.css"
import "./styles/extra2.css"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />

        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        <meta name="color-scheme" content="light only" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="google" content="notranslate" />
        <title>Wedding - Art Blue Java</title>
        <meta name="title" content="Wedding  - Art Blue Java" />
        <meta name="description" content="Undangna adat jawa / java wayang tanpa foto dengan warna biru dan art style - Undangan Online: Undangan digital modern untuk pernikahan dan acara spesial lainnya." />
        <link rel="icon" type="image/x-icon" href="https://satumomen.com/favicon.ico" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://satumomen.com/preview/art-blue-java" />
        <meta property="og:title" content="Wedding  - Art Blue Java" />
        <meta property="og:description" content="Undangna adat jawa / java wayang tanpa foto dengan warna biru dan art style - Undangan Online: Undangan digital modern untuk pernikahan dan acara spesial lainnya." />
        <meta property="og:image" content="https://satumomen.com/themes/art-blue-java/art-blue-java.webp" />

        <link rel="preconnect" href="https://fonts.googleapis.com/" />
        <link rel="preconnect" href="https://fonts.gstatic.com/"  />

        {/* <script type="application/ld+json">
            {
                "@context": "https://schema.org/",
                "@type": "Product",
                "name": "Wedding  - Art Blue Java",
                "image": "https://satumomen.com/themes/art-blue-java/art-blue-java.webp",
                "description": "Undangna adat jawa / java wayang tanpa foto dengan warna biru dan art style - Undangan Online: Undangan digital modern untuk pernikahan dan acara spesial lainnya.",
                "brand": {
                    "@type": "Brand",
                    "name": "Satu Momen"
                },
                "review": {
                    "@type": "Review",
                    "reviewRating": {
                        "@type": "Rating",
                        "ratingValue": "5",
                        "bestRating": "5"
                    },
                    "author": {
                        "@type": "Person",
                        "name": "Elsa Gunayanti"
                    }
                },
                "aggregateRating": {
                    "@type": "AggregateRating",
                    "ratingValue": "4.9",
                    "reviewCount": "579"
                },
                "offers": {
                    "@type": "Offer",
                    "url": "https://satumomen.com/harga",
                    "priceCurrency": "IDR",
                    "price": "85000",
                    "availability": "https://schema.org/InStock",
                    "itemCondition": "https://schema.org/NewCondition"
                }
            }
        </script> */}

    </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
